server:
  port: 10804
spring:
  datasource:
    username: root
    password: passw0rd
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true   # 格式化SQL语句