server:
  port: 10807

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        # 使用druid数据源
        # type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configLocation: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.hacz.edu.*.entity

#pagehelper
pagehelper:
    helperDialect: mariadb
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql