server:
  port: 10901
  tomcat:
    uri-encoding: utf-8
spring:
  redis:
    database: 0  # Redis数据库索引（默认为0）
    password:  # Redis服务器连接密码（默认为空）
    host: 127.0.0.1  # Redis服务器地址
    port: 6379 # Redis服务器连接端口